# -*- coding: utf-8 -*-
"""feedforward_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5DoloRFKwKoUdfmRdigba0dIOjNHltw
"""

import torch
from torch import nn

class FeedForward(nn.Module):
  def __init__(self, d_model, d_ff):
    super().__init__()

    self.Sequential = nn.Sequential(
        nn.Linear(d_model, d_ff),
        nn.ReLU(),
        nn.Linear(d_ff,d_model)
    )

  def forward(self,x):
    x = self.Sequential(x)
    return x