# -*- coding: utf-8 -*-
"""transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWHUO5PwuUi36zjwcZauUXjQ6j61e2uv
"""

import torch
from torch import nn
import math

from transformer.positional_encoding import PositionalEncoding
from transformer.multihead_attention import MultiHeadAttention
from transformer.feedforward_network import FeedForward
from transformer.encoder import EncoderBlock
from transformer.encoder import Encoder
from transformer.decoder import DecoderBlock
from transformer.decoder import Decoder

class Transformer(nn.Module):
  def __init__(self, src_vocab_size, tgt_vocab_size, max_len, d_model, num_heads, d_ff, drop_out, N):
    super().__init__()

    self.d_model = d_model

    self.src_Embedding = nn.Embedding(src_vocab_size, d_model)
    #self.tgt_Embedding = nn.Embedding(tgt_vocab_size, d_model)
    self.tgt_Embedding = self.src_Embedding # Weight tying for joint BPE

    self.Pos_Encoding = PositionalEncoding(max_len,d_model)

    nn.init.normal_(self.src_Embedding.weight, 0, 1.0 / math.sqrt(d_model)) # Xavier init
    nn.init.normal_(self.tgt_Embedding.weight, 0, 1.0 / math.sqrt(d_model))

    self.Encoder = Encoder(d_model, num_heads, d_ff, drop_out, N)
    self.Decoder = Decoder(d_model, num_heads, d_ff, drop_out, N)

    self.FC = nn.Linear(d_model, tgt_vocab_size)
    self.FC.weight = self.tgt_Embedding.weight # Weight tying as the paper

  def forward(self, src, tgt):
    src_embed = self.src_Embedding(src) * math.sqrt(self.d_model) # Scaling for PE
    src_embed = self.Pos_Encoding(src_embed)

    tgt_embed = self.tgt_Embedding(tgt) * math.sqrt(self.d_model) # Scaling for PE
    tgt_embed = self.Pos_Encoding(tgt_embed)

    E = self.Encoder(src_embed)
    D = self.Decoder(tgt_embed, E)

    out = self.FC(D)

    return out